[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
evmVersion = "cancun"
verbosity = 3
isolate = true # for testing transient storage

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
